### ISSUE TITLE
hzero-ui css 样式bug

### ISSUE THREAD

**Issue by pbwei** [open-hand/choerodon-ui#1073]
![image](https://user-images.githubusercontent.com/4220231/162566248-d04dd047-cc73-4514-9626-7c9c59952058.png)
.ant-table.resizable-table table {
  table-layout: fixed;
}
hzero-ui table组件 这个样式，影响页面布局，
[hzero-ui](https://code.choerodon.com.cn/hzero-hzero/hzero-ui/issues)
![image](https://user-images.githubusercontent.com/4220231/162566345-ff0dfdea-6cd8-4bf1-b696-66daef427737.png)
版本号 1.0.84

**Comment by pbwei** [comment]
干掉 
.ant-table.resizable-table table {
table-layout: fixed;
}
这个 样式就对了

**Comment by pbwei** [comment]
麻烦大佬帮我反馈一下，
https://code.choerodon.com.cn/hzero-hzero/hzero-ui/issues
这个 我们进不去

**Comment by Huihuawk** [comment]
> 麻烦大佬帮我反馈一下， https://code.choerodon.com.cn/hzero-hzero/hzero-ui/issues 这个 我们进不去
好 我反馈一下，项目上可以暂时 全局覆盖样式。hzero ui 不维护了，不清楚会不会修复发版。
