### ISSUE TITLE
高级组件 table 组件和 

### ISSUE THREAD

**Issue by pbwei** [open-hand/choerodon-ui#1076]
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

table 
package.json 1.2.0

**Comment by chenyangi3** [comment]
哥们，这个问题解决了吗

**Comment by Huihuawk** [comment]
Check whether the corresponding react and react-dom versions meet the component library restrictions
