### ISSUE TITLE
使用umi脚手架搭建的项目引入choerodon ui 出错

### ISSUE THREAD

**Issue by Chuchudongren** [open-hand/choerodon-ui#1425]
复现步骤：
1、使用umi脚手架搭建项目
npm i @ant-design/pro-cli -g
pro create myapp
2、安装choerodon依赖
yarn add choerodon-ui axios@0.19.1 mobx@4.15.7 mobx-react@6.1.5 mobx-react-lite@1.5.2 react-scripts@4.0.3
3、引入choerodon pro 的组件
import { Button } from 'choerodon-ui/pro';
现象：引用pro的组件报错，引入基础的‘choerodon-ui’可以正常使用。
分析：我在根文件引入
import 'choerodon-ui/lib/configure';
以及修改适配的版本依赖至：
"choerodon-ui": "^1.5.1",
"mobx": "4.15.7",
"mobx-react": "6.1.5",
"mobx-react-lite": "1.5.2",
"react": "^16.12.0",
"react-dom": "^16.8.6",
"react-scripts": "4.0.3",
结果没有正常使用，依然报错。
![image](https://user-images.githubusercontent.com/85165276/215309752-41b0dc7b-795e-47de-83ed-47a717024a6f.png)

**Comment by Huihuawk** [comment]
![image](https://user-images.githubusercontent.com/24917797/221746260-284a537a-d7f1-4bc8-a1d7-d30d61a710a1.png)
试试
