### ISSUE TITLE
dataSet 中的多个queryFields联动问题

### ISSUE THREAD

**Issue by swliu920322** [open-hand/choerodon-ui#1450]
比如，我有2个queryField都是字典项，第二个依赖第一个，当第一个没选的时候，第二个禁用，第一个选了，第二个可以选，第一个切换了，第二个自动清空，使用dataSet的queryFields如何实现

**Comment by Huihuawk** [comment]
配置查询字段属性，cascadeMap；可参考 lov 或 select 组件的级联demo

**Comment by swliu920322** [comment]
有我试了下cascadeMap，第二个联动是走后端api的，第一个选中，第二个可编辑了，但是点进去闪一下，接口也发出了也有返回值。但是再点一下，就显示没有匹配的结果

**Comment by Huihuawk** [comment]
> 但是再点一下，就显示没有匹配的结果

再点一下就没匹配结果是啥意思？开放平台提个工单补个录屏吧

**Comment by zprial** [comment]
+1，我也有这疑问，猜测是被 cascadeMap 过滤了，但是接口返回的数据里面没有个parentCode去匹配，导致可选项为空了
