### ISSUE TITLE
使用dataSet方式进行Tree构建，无法触发select和unselect方法

### ISSUE THREAD

**Issue by 522406840** [open-hand/choerodon-ui#1464]
在使用dataSet构建Tree的例子中，无法触发dataSetde events中的select和unselect方法？求解

**Comment by Huihuawk** [comment]
可以看看这两个例子区别：
https://open.hand-china.com/choerodon-ui/zh/procmp/data-display/tree#%E5%8F%AA%E4%BD%BF%E7%94%A8%20check%20%E5%8A%9F%E8%83%BD

https://open.hand-china.com/choerodon-ui/zh/procmp/data-display/tree#check%E5%92%8Cexpand%E4%BD%BF%E7%94%A8
![image](https://user-images.githubusercontent.com/24917797/221745954-394c194f-aa99-4dca-93d0-7ce6a6d18cd3.png)
文本点击和checkBox 点击是两个处理
