### ISSUE TITLE
怎么自定义表单控件？

### ISSUE THREAD

**Issue by zprial** [open-hand/choerodon-ui#1508]
如题，官网搜索「自定义表单控件」跳转的是空白页
![image](https://user-images.githubusercontent.com/33095380/232177290-7048a17e-8003-4eaf-9541-255907c5162a.png)

**Comment by zprial** [comment]
补充一下，可能是 Cascader 的问题，表单提交的时候拿不到 Cascader 的值

**Comment by Huihuawk** [comment]
> 补充一下，可能是 Cascader 的问题，表单提交的时候拿不到 Cascader 的值

关联DS name 提交应该是能拿到的
官网demo：https://open.hand-china.com/choerodon-ui/zh/procmp/data-entry/cascader#%E6%95%B0%E6%8D%AE%E6%BA%90%E9%80%89%E9%A1%B9
