### ISSUE TITLE
Error: [MobX] 'has()' can only be used on observable objects, arrays and maps

### ISSUE THREAD

**Issue by surongmin** [open-hand/choerodon-ui#299]
Error: [MobX] 'has()' can only be used on observable objects, arrays and maps
▶ 36 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by Huihuawk** [comment]
mobx version：
"mobx": "4.7.0",
"mobx-react": "~6.1.1",
