### ISSUE TITLE
Unhandled Rejection (Error): [MobX] 'has()' can only be used on observable objects, arrays and maps

### ISSUE THREAD

**Issue by FredaMJ95** [open-hand/choerodon-ui#300]
Unhandled Rejection (Error): [MobX] 'has()' can only be used on observable objects, arrays and maps

import React from 'react';
import { Table } from 'choerodon-ui/pro';
export default class BusinessTrip extends React.Component {
    render(){
        return < Table columns={[]} dataSource={[]} / >
    }
}

从choerodon-ui/pro中引用Table或者DataSet并且在页面中使用就会报这个错,有其他人遇到吗 怎么解决的.我的配置文件
[
      'import',
      {
        libraryName: 'choerodon-ui',
        style: true,
      },
      'c7n',
    ],
    [
      'import',
      {
        libraryName: 'choerodon-ui/pro',
        style: true,
      },
      'c7n-pro',
    ],

**Comment by Huihuawk** [comment]
你好，mobx 版本固定一下   
 "mobx": "4.7.0",
   "mobx-react": "~6.1.1",
