### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by surongm** [open-hand/choerodon-ui#308]
使用import { Table } from 'choerodon-ui/pro';
的Table组件会报下面的错误

TypeError: Cannot read property 'length' of undefined
Table.renderTable
D:/Microsoft VS Code/project/PH/powerpip-choerodon-demo/table/Table.js:649
  646 | const { rowSelection } = this.props;
  647 | const prefixCls = this.getPrefixCls();
  648 | const columns = this.columns.concat();
> 649 | if (rowSelection) {
      | ^  650 |     const data = this.getFlatCurrentPageData().filter((item, index) => {
  651 |         if (rowSelection.getCheckboxProps) {
  652 |             return !this.getCheckboxPropsByItem(item, index).disabled;

**Comment by Huihuawk** [comment]
你好，我们发布了稳定 1.0.0 版本，更新了官网以及添加了引导教程。帮助您学习和入门 c7n pro.如果有其他问题可以给我们提工单或者再论坛上交流提问。
