### ISSUE TITLE
Uncaught (in promise) Error: Request failed with status code 404

### ISSUE THREAD

**Issue by surongm** [open-hand/choerodon-ui#309]
![image](https://user-images.githubusercontent.com/41141486/102859839-b2fa4b00-4467-11eb-948b-1d2245565f1e.png)

使用import {Table } from 'choerodon-ui/pro';

createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16)
    at settle (settle.js:17)
    at MockXMLHttpRequest.handleLoad [as onreadystatechange] (xhr.js:62)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8476)
    at XMLHttpRequest.handle (mock.js:8304)
createError @ createError.js:16
settle @ settle.js:17
handleLoad @ xhr.js:62
dispatchEvent @ mock.js:8476
handle @ mock.js:8304
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchLovConfig @ Field.js:525
(anonymous) @ Field.js:66
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
Field @ Field.js:60
(anonymous) @ DataSet.js:1133
processIntlField @ utils.js:594
addField @ DataSet.js:1132
executeAction @ mobx.module.js:191
res @ mobx.module.js:183
(anonymous) @ DataSet.js:1118
initFields @ DataSet.js:1115
(anonymous) @ DataSet.js:67
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
DataSet @ DataSet.js:41
initQueryDataSet @ DataSet.js:1368
(anonymous) @ DataSet.js:69
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
DataSet @ DataSet.js:41
(anonymous) @ index.js:37
./src/components/TableDemo2/index.js @ index.js:297
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ App.css?dde5:82
./src/App.js @ App.js:20
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ index.css?bb0a:82
./src/index.js @ index.js:17
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:17
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 17 more frames
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16)
    at settle (settle.js:17)
    at MockXMLHttpRequest.handleLoad [as onreadystatechange] (xhr.js:62)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8476)
    at XMLHttpRequest.handle (mock.js:8304)
createError @ createError.js:16
settle @ settle.js:17
handleLoad @ xhr.js:62
dispatchEvent @ mock.js:8476
handle @ mock.js:8304
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchLovConfig @ Field.js:525
(anonymous) @ Field.js:66
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
Field @ Field.js:60
(anonymous) @ Record.js:524
processIntlField @ utils.js:594
addField @ Record.js:523
executeAction @ mobx.module.js:191
res @ mobx.module.js:183
(anonymous) @ Record.js:519
initFields @ Record.js:519
(anonymous) @ Record.js:43
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
Record @ Record.js:28
create @ DataSet.js:658
(anonymous) @ DataSet.js:118
(anonymous) @ _baseDelay.js:18
setTimeout (async)
baseDelay @ _baseDelay.js:18
(anonymous) @ defer.js:23
apply @ _apply.js:15
(anonymous) @ _overRest.js:32
(anonymous) @ DataSet.js:116
(anonymous) @ DataSet.js:115
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
set @ DataSet.js:111
initQueryDataSet @ DataSet.js:1373
(anonymous) @ DataSet.js:69
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
DataSet @ DataSet.js:41
(anonymous) @ index.js:37
./src/components/TableDemo2/index.js @ index.js:297
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ App.css?dde5:82
./src/App.js @ App.js:20
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ index.css?bb0a:82
./src/index.js @ index.js:17
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:17
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
construct.js:19 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16)
    at settle (settle.js:17)
    at MockXMLHttpRequest.handleLoad [as onreadystatechange] (xhr.js:62)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8476)
    at XMLHttpRequest.handle (mock.js:8304)
_construct @ construct.js:19
Wrapper @ wrapNativeSuper.js:26
(anonymous) @ DataSetComponent.js:33
DataSetRequestError @ DataSetRequestError.js:4
_callee9$ @ DataSet.js:1449
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_throw @ asyncToGenerator.js:29
Promise.catch (async)
add @ PromiseQueue.js:25
executeAction @ mobx.module.js:191
res @ mobx.module.js:183
query @ DataSet.js:439
(anonymous) @ DataSet.js:78
executeAction @ mobx.module.js:191
runInAction @ mobx.module.js:375
DataSet @ DataSet.js:41
(anonymous) @ index.js:37
./src/components/TableDemo2/index.js @ index.js:297
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ App.css?dde5:82
./src/App.js @ App.js:20
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ index.css?bb0a:82
./src/index.js @ index.js:17
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:17
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16)
    at settle (settle.js:17)
    at MockXMLHttpRequest.handleLoad [as onreadystatechange] (xhr.js:62)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8476)
    at XMLHttpRequest.handle (mock.js:8304)

**Comment by Huihuawk** [comment]
你好，我们发布了稳定 1.0.0 版本，更新了官网以及添加了引导教程。帮助您学习和入门 c7n pro.如果有其他问题可以给我们提工单或者再论坛上交流提问。
