### ISSUE TITLE
Pro Tree has performence issue

### ISSUE THREAD

**Issue by hb407033** [open-hand/choerodon-ui#319]
Tree pro components has worse performence, when  load more than 2000 records, cause chrome crash

**Comment by Huihuawk** [comment]
> Tree pro components has worse performence, when load more than 2000 records, cause chrome crash

We recommend that you use an asynchronous loading scheme to deal with lag problems.We will optimize its performance in the future.

**Comment by hb407033** [comment]
i have changed to asynchronous load it`s better now , thanks
