### ISSUE TITLE
文档中的图片全部挂了

### ISSUE THREAD

**Issue by zqjimlove** [open-hand/choerodon-ui#409]
用了图床的图片都看不了

**Comment by Huihuawk** [comment]
哪个地址？

**Comment by zqjimlove** [comment]
https://open-hand.github.io/choerodon-ui/zh/tutorials/basic
https://open-hand.gitee.io/choerodon-ui/zh/tutorials/basic

都不显示

**Comment by Huihuawk** [comment]
没有看到挂掉。https://open-hand.gitee.io/choerodon-ui/zh/tutorials/basic
![image](https://user-images.githubusercontent.com/24917797/116338917-1974e880-a80f-11eb-8bce-1ebd07524cb6.png)
