### ISSUE TITLE
【ERROR】：feedback参数类型错误

### ISSUE THREAD

**Issue by linyun-git** [open-hand/choerodon-ui#584]
## DataSetProps的feedback属性与文档不一致
文档中提示feedback的类型应为Feedback，但实际在typescript中要求的类型为TransportProps

**Comment by HughHzWu** [comment]
> ## DataSetProps的feedback属性与文档不一致
> 文档中提示feedback的类型应为Feedback，但实际在typescript中要求的类型为TransportProps

您好， 感谢提供issue，该问题是ts的问题， 将在1.4.4版本中修复
