### ISSUE TITLE
[BUG]: Table 组件个性化 customizedCode 变化没有触发列更新

### ISSUE THREAD

**Issue by dishui1238** [open-hand/choerodon-ui#603]
1. 问题描述
 当传递 customizable 属性时，前后传递 customizedCode 参数不一致，没有触发 loadCustomized 函数，页面列展示没有任何变化（代码：master 分支 TableStore 文件 1297 行）。
 2. 期望效果
 期望 customizedCode 变化时可以触发列样式的更新；
 动态添加 customizable、customizedCode 属性时，期望可以触发列更新，而不是Table 初始化时就需要添加 customizable 属性；

使用版本：1.3.2； 测试版本：1.3.2、1.4.4

**Comment by HughHzWu** [comment]
感谢提供issue， 该问题已修正，将在下个版本中修复
