### ISSUE TITLE
Pro 组件中的 Tree 树形控件在异步加载时有个Bug

### ISSUE THREAD

**Issue by yandif** [open-hand/choerodon-ui#612]
## Bug描述
当调用 dataSet 的 query 方法进行重新查询数据后，已经展开的节点的子节异步加载不了。
需要重新渲染 Tree 组件才能正常显示。
## 截图
![GIF 2021-9-10 14-58-16](https://user-images.githubusercontent.com/52165593/132813154-3535cde7-5041-4b03-8436-178422b0f8ea.gif)

## 重现链接: 
https://open-hand.gitee.io/choerodon-ui/zh/procmp/data-display/tree#%E5%BC%82%E6%AD%A5%E5%8A%A0%E8%BD%BD

**Comment by Huihuawk** [comment]
感谢提供issue， 该问题已修复。注意发版公告
