### ISSUE TITLE
npm仓库提示没有choerodon-ui，怎么处理？

### ISSUE THREAD

**Issue by chenyangi3** [open-hand/choerodon-ui#897]
![image](https://user-images.githubusercontent.com/22334523/149283881-2ad5a4f8-3233-4948-8b62-868a364aeb4a.png)

想安装1.5.1的，发现安不上
node版本：v10.15.1
yarn版本：v1.22.4

**Comment by Huihuawk** [comment]
你安装依赖包的源 是什么？重试一下？如果对应源没同步 找相关人员同步更新一下
公库是没问题的：
https://www.npmjs.com/package/choerodon-ui
