### ISSUE TITLE
1.5.1和1.5.0版本choerodon-ui/pro有问题

### ISSUE THREAD

**Issue by mailworks** [open-hand/choerodon-ui#909]
按照官网文档示例教程配置好后写一个Button，没有“choerodon-ui 的蓝色按钮组件”
参考教程：https://open-hand.github.io/choerodon-ui/zh/tutorials/demo-build
依赖配置：
  "axios": "^0.24.0",
    "choerodon-ui": "1.5.1",
    "mobx": "~4.15.7",
    "mobx-react": "~6.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^2.1.3"

将choerodon-ui降级到1.4.5没问题

**Comment by Huihuawk** [comment]
react@16.12.0
react-dom@16.8.6

react 对应版本用这个。然后根路径引入一下 
import "choerodon-ui/lib/configure";

**Comment by mailworks** [comment]
可以了，希望文档能明确下choerodon-ui所依赖的宿主环境版本号
CRA
react
mobx
mobx-react

**Comment by mailworks** [comment]
VM778:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload 

报这个错误是什么原因呢？

> react@16.12.0 react-dom@16.8.6
> 
> react 对应版本用这个。然后根路径引入一下 import "choerodon-ui/lib/configure";

**Comment by Huihuawk** [comment]
好的 文档我们会再完善一下。这个报错你具体调试看看 不太清楚报错原因
