### ISSUE TITLE
choerodon-ui 是否考虑支持vue版本

### ISSUE THREAD

**Issue by zhuangxiaohui** [open-hand/choerodon-ui#979]
该UI挺不错的，很多功能都很全面
choerodon-ui 是否考虑支持vue版本
支持vue2，vue3版本

**Comment by Huihuawk** [comment]
暂不支持，后续可以考虑规划。
有移动版：https://hips-vue-ui.open-front.hand-china.com/#/zh-CN/quickstart
https://open.hand-china.com/document-center/doc/component/1826/16300?doc_id=160513&doc_code=8953
