### ISSUE TITLE
无法启动，运行失败

### ISSUE THREAD

**Issue by diy4869** [open-hand/choerodon-ui#990]
下载了项目，通过 `npm install` 进行安装依赖，安装完成后，通过`npm run start` 进行启动，但是启动失败。也尝试过 通过` npm run site-dev`进行启动，也失败。
![image](https://user-images.githubusercontent.com/29079700/155836384-2684f92e-3f09-4d38-947b-cc7119eb854d.png)

- node version：16.13.1
- npm version：8.1.2
- win10

**Comment by Huihuawk** [comment]
node 版本降到 12.17.0 或者 12.22.0 重新装包启动试试，

**Comment by diy4869** [comment]
换成 12.17 ，执行 npm run start 倒是成功运行了，但是和官网文档 好像不太一样，比较好奇官网文档的编辑功能是怎么实现的

**Comment by Huihuawk** [comment]
官网文档是另外一个项目，是个 GATSBY 文档工程，在线编辑功能比较麻烦，你可以参考 antv GATSBY文档工程项目，原理差不多。
